import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { createRequire } from "module";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const solc = require("solc");

const contractPath = resolve(__dirname, "../contracts/MemeToken.sol");
const source = readFileSync(contractPath, "utf8");

const input = {
  language: "Solidity",
  sources: {
    "MemeToken.sol": { content: source },
  },
  settings: {
    outputSelection: {
      "*": {
        "*": ["abi", "evm.bytecode.object"],
      },
    },
    optimizer: { enabled: true, runs: 200 },
  },
};

console.log("Compiling MemeToken.sol...");
const output = JSON.parse(solc.compile(JSON.stringify(input)));

if (output.errors) {
  const errors = output.errors.filter((e) => e.severity === "error");
  if (errors.length > 0) {
    console.error("Compilation errors:", errors);
    process.exit(1);
  }
  output.errors.forEach((e) => console.warn(e.formattedMessage));
}

const contract = output.contracts["MemeToken.sol"]["MemeToken"];
const abi = contract.abi;
const bytecode = "0x" + contract.evm.bytecode.object;

const outDir = resolve(__dirname, "../src/lib");
mkdirSync(outDir, { recursive: true });

const artifact = `// Auto-generated by scripts/compile-erc20.mjs — do not edit manually.
// Compiled from contracts/MemeToken.sol

export const MEME_TOKEN_ABI = ${JSON.stringify(abi, null, 2)} as const;

export const MEME_TOKEN_BYTECODE = "${bytecode}" as const;
`;

writeFileSync(resolve(outDir, "erc20-artifact.ts"), artifact);
console.log("✅ Generated src/lib/erc20-artifact.ts");
console.log("   ABI entries:", abi.length);
console.log("   Bytecode size:", Math.round(bytecode.length / 2), "bytes");
